export type DistrictEntry = {
  state: string;
  district: string;
};

export const indiaStates = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
  "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Delhi", "Chandigarh", "Jammu & Kashmir", "Ladakh", "Puducherry",
];

export const indiaDistricts: DistrictEntry[] = [
  // Andhra Pradesh
  { state: "Andhra Pradesh", district: "Anantapur" },
  { state: "Andhra Pradesh", district: "Chittoor" },
  { state: "Andhra Pradesh", district: "East Godavari" },
  { state: "Andhra Pradesh", district: "Guntur" },
  { state: "Andhra Pradesh", district: "Krishna" },
  { state: "Andhra Pradesh", district: "Kurnool" },
  { state: "Andhra Pradesh", district: "Nellore" },
  { state: "Andhra Pradesh", district: "Prakasam" },
  { state: "Andhra Pradesh", district: "Srikakulam" },
  { state: "Andhra Pradesh", district: "Visakhapatnam" },
  { state: "Andhra Pradesh", district: "Vizianagaram" },
  { state: "Andhra Pradesh", district: "West Godavari" },
  { state: "Andhra Pradesh", district: "YSR Kadapa" },
  // Assam
  { state: "Assam", district: "Barpeta" },
  { state: "Assam", district: "Cachar" },
  { state: "Assam", district: "Dibrugarh" },
  { state: "Assam", district: "Kamrup Metro" },
  { state: "Assam", district: "Jorhat" },
  { state: "Assam", district: "Nagaon" },
  { state: "Assam", district: "Sivasagar" },
  { state: "Assam", district: "Sonitpur" },
  { state: "Assam", district: "Tinsukia" },
  // Bihar
  { state: "Bihar", district: "Araria" },
  { state: "Bihar", district: "Aurangabad" },
  { state: "Bihar", district: "Bhagalpur" },
  { state: "Bihar", district: "Gaya" },
  { state: "Bihar", district: "Muzaffarpur" },
  { state: "Bihar", district: "Nalanda" },
  { state: "Bihar", district: "Patna" },
  { state: "Bihar", district: "Purnia" },
  { state: "Bihar", district: "Rohtas" },
  { state: "Bihar", district: "Sitamarhi" },
  // Chhattisgarh
  { state: "Chhattisgarh", district: "Bastar" },
  { state: "Chhattisgarh", district: "Bilaspur" },
  { state: "Chhattisgarh", district: "Durg" },
  { state: "Chhattisgarh", district: "Raigarh" },
  { state: "Chhattisgarh", district: "Raipur" },
  { state: "Chhattisgarh", district: "Rajnandgaon" },
  // Delhi
  { state: "Delhi", district: "Central Delhi" },
  { state: "Delhi", district: "East Delhi" },
  { state: "Delhi", district: "New Delhi" },
  { state: "Delhi", district: "North Delhi" },
  { state: "Delhi", district: "North East Delhi" },
  { state: "Delhi", district: "North West Delhi" },
  { state: "Delhi", district: "Shahdara" },
  { state: "Delhi", district: "South Delhi" },
  { state: "Delhi", district: "South East Delhi" },
  { state: "Delhi", district: "South West Delhi" },
  { state: "Delhi", district: "West Delhi" },
  // Goa
  { state: "Goa", district: "North Goa" },
  { state: "Goa", district: "South Goa" },
  // Gujarat
  { state: "Gujarat", district: "Ahmedabad" },
  { state: "Gujarat", district: "Amreli" },
  { state: "Gujarat", district: "Anand" },
  { state: "Gujarat", district: "Bharuch" },
  { state: "Gujarat", district: "Bhavnagar" },
  { state: "Gujarat", district: "Gandhinagar" },
  { state: "Gujarat", district: "Jamnagar" },
  { state: "Gujarat", district: "Junagadh" },
  { state: "Gujarat", district: "Kutch" },
  { state: "Gujarat", district: "Rajkot" },
  { state: "Gujarat", district: "Surat" },
  { state: "Gujarat", district: "Vadodara" },
  // Haryana
  { state: "Haryana", district: "Ambala" },
  { state: "Haryana", district: "Faridabad" },
  { state: "Haryana", district: "Gurugram" },
  { state: "Haryana", district: "Hisar" },
  { state: "Haryana", district: "Karnal" },
  { state: "Haryana", district: "Panipat" },
  { state: "Haryana", district: "Rohtak" },
  { state: "Haryana", district: "Sonipat" },
  { state: "Haryana", district: "Yamunanagar" },
  // Himachal Pradesh
  { state: "Himachal Pradesh", district: "Chamba" },
  { state: "Himachal Pradesh", district: "Kangra" },
  { state: "Himachal Pradesh", district: "Kullu" },
  { state: "Himachal Pradesh", district: "Mandi" },
  { state: "Himachal Pradesh", district: "Shimla" },
  { state: "Himachal Pradesh", district: "Solan" },
  // Jharkhand
  { state: "Jharkhand", district: "Bokaro" },
  { state: "Jharkhand", district: "Deoghar" },
  { state: "Jharkhand", district: "Dhanbad" },
  { state: "Jharkhand", district: "Giridih" },
  { state: "Jharkhand", district: "Hazaribagh" },
  { state: "Jharkhand", district: "Ranchi" },
  // Karnataka
  { state: "Karnataka", district: "Bagalkot" },
  { state: "Karnataka", district: "Ballari" },
  { state: "Karnataka", district: "Belagavi" },
  { state: "Karnataka", district: "Bengaluru Rural" },
  { state: "Karnataka", district: "Bengaluru Urban" },
  { state: "Karnataka", district: "Bidar" },
  { state: "Karnataka", district: "Chamarajanagar" },
  { state: "Karnataka", district: "Dakshina Kannada" },
  { state: "Karnataka", district: "Davanagere" },
  { state: "Karnataka", district: "Dharwad" },
  { state: "Karnataka", district: "Hassan" },
  { state: "Karnataka", district: "Kalaburagi" },
  { state: "Karnataka", district: "Kodagu" },
  { state: "Karnataka", district: "Kolar" },
  { state: "Karnataka", district: "Mandya" },
  { state: "Karnataka", district: "Mysuru" },
  { state: "Karnataka", district: "Raichur" },
  { state: "Karnataka", district: "Shivamogga" },
  { state: "Karnataka", district: "Tumakuru" },
  { state: "Karnataka", district: "Udupi" },
  { state: "Karnataka", district: "Uttara Kannada" },
  // Kerala
  { state: "Kerala", district: "Alappuzha" },
  { state: "Kerala", district: "Ernakulam" },
  { state: "Kerala", district: "Idukki" },
  { state: "Kerala", district: "Kannur" },
  { state: "Kerala", district: "Kasaragod" },
  { state: "Kerala", district: "Kollam" },
  { state: "Kerala", district: "Kottayam" },
  { state: "Kerala", district: "Kozhikode" },
  { state: "Kerala", district: "Malappuram" },
  { state: "Kerala", district: "Palakkad" },
  { state: "Kerala", district: "Pathanamthitta" },
  { state: "Kerala", district: "Thiruvananthapuram" },
  { state: "Kerala", district: "Thrissur" },
  { state: "Kerala", district: "Wayanad" },
  // Madhya Pradesh
  { state: "Madhya Pradesh", district: "Bhopal" },
  { state: "Madhya Pradesh", district: "Chhindwara" },
  { state: "Madhya Pradesh", district: "Gwalior" },
  { state: "Madhya Pradesh", district: "Indore" },
  { state: "Madhya Pradesh", district: "Jabalpur" },
  { state: "Madhya Pradesh", district: "Morena" },
  { state: "Madhya Pradesh", district: "Rewa" },
  { state: "Madhya Pradesh", district: "Sagar" },
  { state: "Madhya Pradesh", district: "Satna" },
  { state: "Madhya Pradesh", district: "Ujjain" },
  // Maharashtra
  { state: "Maharashtra", district: "Ahmednagar" },
  { state: "Maharashtra", district: "Akola" },
  { state: "Maharashtra", district: "Amravati" },
  { state: "Maharashtra", district: "Aurangabad" },
  { state: "Maharashtra", district: "Beed" },
  { state: "Maharashtra", district: "Bhandara" },
  { state: "Maharashtra", district: "Buldhana" },
  { state: "Maharashtra", district: "Chandrapur" },
  { state: "Maharashtra", district: "Dhule" },
  { state: "Maharashtra", district: "Gadchiroli" },
  { state: "Maharashtra", district: "Jalgaon" },
  { state: "Maharashtra", district: "Jalna" },
  { state: "Maharashtra", district: "Kolhapur" },
  { state: "Maharashtra", district: "Latur" },
  { state: "Maharashtra", district: "Mumbai City" },
  { state: "Maharashtra", district: "Mumbai Suburban" },
  { state: "Maharashtra", district: "Nagpur" },
  { state: "Maharashtra", district: "Nanded" },
  { state: "Maharashtra", district: "Nashik" },
  { state: "Maharashtra", district: "Osmanabad" },
  { state: "Maharashtra", district: "Palghar" },
  { state: "Maharashtra", district: "Parbhani" },
  { state: "Maharashtra", district: "Pune" },
  { state: "Maharashtra", district: "Raigad" },
  { state: "Maharashtra", district: "Ratnagiri" },
  { state: "Maharashtra", district: "Sangli" },
  { state: "Maharashtra", district: "Satara" },
  { state: "Maharashtra", district: "Sindhudurg" },
  { state: "Maharashtra", district: "Solapur" },
  { state: "Maharashtra", district: "Thane" },
  { state: "Maharashtra", district: "Wardha" },
  { state: "Maharashtra", district: "Washim" },
  { state: "Maharashtra", district: "Yavatmal" },
  // Odisha
  { state: "Odisha", district: "Angul" },
  { state: "Odisha", district: "Balasore" },
  { state: "Odisha", district: "Bargarh" },
  { state: "Odisha", district: "Bhadrak" },
  { state: "Odisha", district: "Bhubaneswar (Khordha)" },
  { state: "Odisha", district: "Cuttack" },
  { state: "Odisha", district: "Ganjam" },
  { state: "Odisha", district: "Kendrapara" },
  { state: "Odisha", district: "Koraput" },
  { state: "Odisha", district: "Puri" },
  { state: "Odisha", district: "Sambalpur" },
  { state: "Odisha", district: "Sundargarh" },
  // Punjab
  { state: "Punjab", district: "Amritsar" },
  { state: "Punjab", district: "Bathinda" },
  { state: "Punjab", district: "Faridkot" },
  { state: "Punjab", district: "Ferozepur" },
  { state: "Punjab", district: "Gurdaspur" },
  { state: "Punjab", district: "Hoshiarpur" },
  { state: "Punjab", district: "Jalandhar" },
  { state: "Punjab", district: "Kapurthala" },
  { state: "Punjab", district: "Ludhiana" },
  { state: "Punjab", district: "Moga" },
  { state: "Punjab", district: "Mohali" },
  { state: "Punjab", district: "Pathankot" },
  { state: "Punjab", district: "Patiala" },
  { state: "Punjab", district: "Rupnagar" },
  { state: "Punjab", district: "Sangrur" },
  // Rajasthan
  { state: "Rajasthan", district: "Ajmer" },
  { state: "Rajasthan", district: "Alwar" },
  { state: "Rajasthan", district: "Barmer" },
  { state: "Rajasthan", district: "Bikaner" },
  { state: "Rajasthan", district: "Churu" },
  { state: "Rajasthan", district: "Jodhpur" },
  { state: "Rajasthan", district: "Jaipur" },
  { state: "Rajasthan", district: "Jhalawar" },
  { state: "Rajasthan", district: "Kota" },
  { state: "Rajasthan", district: "Nagaur" },
  { state: "Rajasthan", district: "Sikar" },
  { state: "Rajasthan", district: "Udaipur" },
  // Tamil Nadu
  { state: "Tamil Nadu", district: "Chennai" },
  { state: "Tamil Nadu", district: "Coimbatore" },
  { state: "Tamil Nadu", district: "Cuddalore" },
  { state: "Tamil Nadu", district: "Dharmapuri" },
  { state: "Tamil Nadu", district: "Dindigul" },
  { state: "Tamil Nadu", district: "Erode" },
  { state: "Tamil Nadu", district: "Kanchipuram" },
  { state: "Tamil Nadu", district: "Kanyakumari" },
  { state: "Tamil Nadu", district: "Karur" },
  { state: "Tamil Nadu", district: "Madurai" },
  { state: "Tamil Nadu", district: "Nagapattinam" },
  { state: "Tamil Nadu", district: "Namakkal" },
  { state: "Tamil Nadu", district: "Salem" },
  { state: "Tamil Nadu", district: "Thanjavur" },
  { state: "Tamil Nadu", district: "The Nilgiris" },
  { state: "Tamil Nadu", district: "Tiruchirappalli" },
  { state: "Tamil Nadu", district: "Tirunelveli" },
  { state: "Tamil Nadu", district: "Tirupur" },
  { state: "Tamil Nadu", district: "Tiruvannamalai" },
  { state: "Tamil Nadu", district: "Tuticorin" },
  { state: "Tamil Nadu", district: "Vellore" },
  { state: "Tamil Nadu", district: "Villupuram" },
  { state: "Tamil Nadu", district: "Virudhunagar" },
  // Telangana
  { state: "Telangana", district: "Adilabad" },
  { state: "Telangana", district: "Hyderabad" },
  { state: "Telangana", district: "Karimnagar" },
  { state: "Telangana", district: "Khammam" },
  { state: "Telangana", district: "Mahabubnagar" },
  { state: "Telangana", district: "Medak" },
  { state: "Telangana", district: "Nalgonda" },
  { state: "Telangana", district: "Nizamabad" },
  { state: "Telangana", district: "Rangareddy" },
  { state: "Telangana", district: "Warangal" },
  // Uttar Pradesh
  { state: "Uttar Pradesh", district: "Agra" },
  { state: "Uttar Pradesh", district: "Aligarh" },
  { state: "Uttar Pradesh", district: "Allahabad (Prayagraj)" },
  { state: "Uttar Pradesh", district: "Azamgarh" },
  { state: "Uttar Pradesh", district: "Bahraich" },
  { state: "Uttar Pradesh", district: "Ballia" },
  { state: "Uttar Pradesh", district: "Bareilly" },
  { state: "Uttar Pradesh", district: "Bijnor" },
  { state: "Uttar Pradesh", district: "Bulandshahr" },
  { state: "Uttar Pradesh", district: "Etah" },
  { state: "Uttar Pradesh", district: "Farrukhabad" },
  { state: "Uttar Pradesh", district: "Firozabad" },
  { state: "Uttar Pradesh", district: "Ghaziabad" },
  { state: "Uttar Pradesh", district: "Gorakhpur" },
  { state: "Uttar Pradesh", district: "Jhansi" },
  { state: "Uttar Pradesh", district: "Kanpur Nagar" },
  { state: "Uttar Pradesh", district: "Lucknow" },
  { state: "Uttar Pradesh", district: "Mathura" },
  { state: "Uttar Pradesh", district: "Meerut" },
  { state: "Uttar Pradesh", district: "Moradabad" },
  { state: "Uttar Pradesh", district: "Muzaffarnagar" },
  { state: "Uttar Pradesh", district: "Noida (Gautam Buddha Nagar)" },
  { state: "Uttar Pradesh", district: "Raebareli" },
  { state: "Uttar Pradesh", district: "Saharanpur" },
  { state: "Uttar Pradesh", district: "Shahjahanpur" },
  { state: "Uttar Pradesh", district: "Sitapur" },
  { state: "Uttar Pradesh", district: "Varanasi" },
  // Uttarakhand
  { state: "Uttarakhand", district: "Dehradun" },
  { state: "Uttarakhand", district: "Haridwar" },
  { state: "Uttarakhand", district: "Nainital" },
  { state: "Uttarakhand", district: "Pauri Garhwal" },
  { state: "Uttarakhand", district: "Tehri Garhwal" },
  { state: "Uttarakhand", district: "Udham Singh Nagar" },
  // West Bengal
  { state: "West Bengal", district: "Bankura" },
  { state: "West Bengal", district: "Barddhaman" },
  { state: "West Bengal", district: "Birbhum" },
  { state: "West Bengal", district: "Cooch Behar" },
  { state: "West Bengal", district: "Darjeeling" },
  { state: "West Bengal", district: "Hooghly" },
  { state: "West Bengal", district: "Howrah" },
  { state: "West Bengal", district: "Jalpaiguri" },
  { state: "West Bengal", district: "Kolkata" },
  { state: "West Bengal", district: "Malda" },
  { state: "West Bengal", district: "Murshidabad" },
  { state: "West Bengal", district: "Nadia" },
  { state: "West Bengal", district: "North 24 Parganas" },
  { state: "West Bengal", district: "Paschim Medinipur" },
  { state: "West Bengal", district: "Purba Medinipur" },
  { state: "West Bengal", district: "Purulia" },
  { state: "West Bengal", district: "South 24 Parganas" },
  { state: "West Bengal", district: "Uttar Dinajpur" },
  // J&K and others
  { state: "Jammu & Kashmir", district: "Anantnag" },
  { state: "Jammu & Kashmir", district: "Baramulla" },
  { state: "Jammu & Kashmir", district: "Jammu" },
  { state: "Jammu & Kashmir", district: "Kathua" },
  { state: "Jammu & Kashmir", district: "Srinagar" },
  { state: "Jammu & Kashmir", district: "Udhampur" },
  { state: "Chandigarh", district: "Chandigarh" },
  { state: "Puducherry", district: "Karaikal" },
  { state: "Puducherry", district: "Puducherry" },
];

export function getDistrictsByState(state: string): string[] {
  return indiaDistricts
    .filter((d) => d.state === state)
    .map((d) => d.district);
}
